version: "3.8"
services:
  django:
    image: dgango
    build: 
      context: .
    ports:
      - 8000:8000
    # expose:
    #   - "8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - .env
    restart: always
    