apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgresdb
        image: postgres
        imagePullPolicy: "IfNotPresent"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_NAME
            valueFrom:
              secretKeyRef:
                key: postgres_name
                name: postgres-secrets
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: postgres_user
                name: postgres-secrets
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgres_password
                name: postgres-secrets
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                key: postgres_host
                name: postgres-secrets
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgresdb
          - name: postgres-secrets
            mountPath: /etc/postgres-secrets
            readOnly: true
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: postgres-secrets
          secret:
            secretName: postgres-secrets