apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
data:
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLT0wa242ZXNjbHMrbEBAd28oQHo0YzVkZ3BhLWpAOCE2LWowbW1iYWo1YjYmM3BuaG42
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
